package com.databuff.apm.common.meta;

import com.databuff.apm.common.serde.DcSpanUtil;
import com.databuff.apm.common.model.DcSpan;
import com.databuff.apm.common.util.ServiceKeyUtil;

import java.util.Locale;
import java.util.Map;
import java.util.Set;

/**
 * 从出站组件 span 解析虚拟服务名与实例，与历史 portal {@code OutProcessor#initComponentService} 行为一致。
 */
public final class VirtualServiceResolver {

    public record ResolvedVirtualService(
            String serviceId,
            String service,
            String serviceInstance,
            String serviceType,
            String typeIcon,
            String hostname,
            String ports) {
    }

    private VirtualServiceResolver() {
    }

    public static ResolvedVirtualService resolve(DcSpan span) {
        return resolve(span, Set.of());
    }

    public static ResolvedVirtualService resolve(DcSpan span, Set<String> tracedServices) {
        if (span == null || span.isOut != 1) {
            return null;
        }
        Map<String, String> meta = OtelAttributeMaps.parse(span);
        VirtualComponentNaming.NamedInstance named = resolveNamedInstance(span, meta, tracedServices);
        if (named == null || named.service().isBlank() || named.serviceInstance().isBlank()) {
            return null;
        }
        String serviceId = ServiceKeyUtil.of(named.service());
        ServiceTypeClassifier.Classification classified = ServiceTypeClassifier.classify(named.service());
        String hostname = firstNonBlank(
                named.serviceInstance(),
                span.hostName,
                OtelAttributeMaps.firstNonBlank(meta, "server.address", "net.peer.name", "host.name"));
        String ports = resolvePorts(meta, named.serviceInstance());
        return new ResolvedVirtualService(
                serviceId,
                named.service(),
                named.serviceInstance(),
                classified.serviceType(),
                classified.type(),
                nullToEmpty(hostname),
                nullToEmpty(ports));
    }

    private static VirtualComponentNaming.NamedInstance resolveNamedInstance(
            DcSpan span, Map<String, String> meta, Set<String> tracedServices) {
        if (DcSpanUtil.isMqSpan(span)) {
            String mqType = OtelAttributeMaps.firstNonBlank(meta, "messaging.system");
            String topic = OtelAttributeMaps.firstNonBlank(
                    meta, "messaging.destination.name", "messaging.kafka.destination");
            String broker = OtelAttributeMaps.firstNonBlank(
                    meta, "net.peer.name", "server.address", "messaging.kafka.broker");
            return VirtualComponentNaming.mq(mqType, topic, broker);
        }
        if (DcSpanUtil.isDbSpan(span) || DcSpanUtil.isRedisSpan(span) || DcSpanUtil.isEsSpan(span) || DcSpanUtil.isConfigSpan(span)) {
            String componentName = componentName(span, meta);
            String dbInstance = OtelAttributeMaps.firstNonBlank(meta, "db.name");
            String peerHost = peerHost(span, meta);
            String peerPort = peerPort(meta);
            return VirtualComponentNaming.resolve(
                    componentName, dbInstance, peerHost, peerPort, span.service);
        }
        // HTTP/RPC remote virtual services are generated by ingest RemoteCallProcessor
        // Legacy portal compatibility (HttpRpcClientOutProcessor); not applied here.
        return null;
    }

    /** Skip virtual external/RPC services when peer is another instrumented service in the same trace. */
    public static boolean isTracedInternalPeer(String peerHost, Set<String> tracedServices) {
        if (peerHost == null || peerHost.isBlank() || tracedServices == null || tracedServices.isEmpty()) {
            return false;
        }
        String normalized = normalizePeerHost(peerHost);
        if (tracedServices.contains(normalized)) {
            return true;
        }
        int dot = normalized.indexOf('.');
        if (dot > 0) {
            return tracedServices.contains(normalized.substring(0, dot));
        }
        return false;
    }

    public static String normalizePeerHost(String peerHost) {
        String host = peerHost.trim().toLowerCase(Locale.ROOT);
        if (host.startsWith("[") && host.contains("]")) {
            host = host.substring(host.indexOf(']') + 1);
        }
        int colon = host.lastIndexOf(':');
        if (colon > 0 && host.substring(colon + 1).chars().allMatch(Character::isDigit)) {
            host = host.substring(0, colon);
        }
        return host;
    }

    private static String componentName(DcSpan span, Map<String, String> meta) {
        if (DcSpanUtil.isRedisSpan(span)) {
            return firstNonBlank(
                    OtelAttributeMaps.firstNonBlank(meta, "db.system", "db.type"),
                    "redis");
        }
        if (DcSpanUtil.isEsSpan(span)) {
            return firstNonBlank(
                    OtelAttributeMaps.firstNonBlank(meta, "db.system", "rpc.system"),
                    "elasticsearch");
        }
        if (DcSpanUtil.isConfigSpan(span)) {
            return firstNonBlank(
                    OtelAttributeMaps.firstNonBlank(meta, "config.type", "db.system", "db.type"),
                    "config");
        }
        return firstNonBlank(
                OtelAttributeMaps.firstNonBlank(meta, "db.system", "db.type"),
                "db");
    }

    private static String peerHost(DcSpan span, Map<String, String> meta) {
        return firstNonBlank(
                span.metaPeerHostname,
                OtelAttributeMaps.firstNonBlank(meta, "server.address", "net.peer.name", "db.connection_string"));
    }

    private static String peerPort(Map<String, String> meta) {
        return OtelAttributeMaps.firstNonBlank(
                meta, "server.port", "net.peer.port", "db.connection_string.port");
    }

    private static String resolvePorts(Map<String, String> meta, String serviceInstance) {
        String explicit = peerPort(meta);
        if (explicit != null && !explicit.isBlank()) {
            return explicit.trim();
        }
        if (serviceInstance != null && serviceInstance.contains(":")) {
            int index = serviceInstance.lastIndexOf(':');
            if (index >= 0 && index + 1 < serviceInstance.length()) {
                return serviceInstance.substring(index + 1);
            }
        }
        return "";
    }

    private static String firstNonBlank(String primary, String... fallbacks) {
        if (primary != null && !primary.isBlank()) {
            return primary.trim();
        }
        if (fallbacks != null) {
            for (String fallback : fallbacks) {
                if (fallback != null && !fallback.isBlank()) {
                    return fallback.trim();
                }
            }
        }
        return null;
    }

    private static String nullToEmpty(String value) {
        return value == null ? "" : value;
    }
}
