// global
export const SET_DURATION_RANGE = 'SET_DURATION_RANGE';
export const SET_DURATION_DATES = 'SET_DURATION_DATES';
export const SET_DURATION_DATES_INIT_STATUS = 'SET_DURATION_DATES_INIT_STATUS';
export const SET_EVENTS = 'SET_EVENTS';
export const RUN_EVENTS = 'RUN_EVENTS';
export const SET_CHARTS = 'SET_CHARTS';
export const CLEAR_CHARTS = 'CLEAR_CHARTS';
export const SET_LOCK = 'SET_LOCK';
export const SET_EDIT = 'SET_EDIT';

// metrics
export const RESET_QUERY_FORM = 'RESET_QUERY_FORM';
export const SET_METRIC_QUERY_FORM = 'SET_METRIC_QUERY_FORM';
export const SET_METRIC_LIST = 'SET_METRIC_LIST';
export const SET_METRIC_DETAIL = 'SET_METRIC_DETAIL';
export const TOGGLE_DETAIL_ACTIVE = 'TOGGLE_DETAIL_ACTIVE';
export const TOGGLE_METRIC_LIST_LOADING = 'TOGGLE_METRIC_LIST_LOADING';
export const TOGGLE_METRIC_DETAIL_LOADING = 'TOGGLE_METRIC_DETAIL_LOADING';

export const SET_TAG_LIST = 'SET_TAG_LIST';
export const SET_TAG_MAPPING = 'SET_TAG_MAPPING';
export const TOGGLE_TAG_SELECT_LOADING = 'TOGGLE_TAG_SELECT_LOADING';
