import { OptionalPropMenu, FullPropMenu } from './route.types';

// 通用的包裹层组件，会在 router/index.ts 中特殊处理
const RouterViewTemp = 'router-view-temp';

// AI 平台 17
const aiPlatform: OptionalPropMenu[] = [
  {
    parentId: 0,
    id: 17,
    name: 'AI 平台',
    path: '/aiPlatform',
    icon: 'db-icon-ai',
    isMenu: true,
    order: 0.5,
  },
  {
    parentId: 17,
    id: 1701,
    name: 'AI 对话',
    path: '/aiPlatform/chat',
    filePath: '/aiPlatform/chat',
    isMenu: true,
    leaf: true,
    order: 1,
    noFooter: true,
  },
  {
    parentId: 17,
    id: 1702,
    name: '工具管理',
    path: '/aiPlatform/tools',
    filePath: '/aiPlatform/tools',
    isMenu: true,
    leaf: true,
    order: 2,
  },
  {
    parentId: 17,
    id: 1703,
    name: '技能管理',
    path: '/aiPlatform/skills',
    filePath: '/aiPlatform/skills',
    isMenu: true,
    leaf: true,
    order: 3,
  },
  {
    parentId: 17,
    id: 1704,
    name: '数字专家',
    path: '/aiPlatform/experts',
    filePath: '/aiPlatform/experts',
    isMenu: true,
    leaf: true,
    order: 4,
  },
];

// 全局大盘 1
const cockpit: OptionalPropMenu[] = [
  {
    parentId: 0,
    id: 1,
    name: '全局大盘',
    path: '/cockpit',
    icon: 'db-icon-cockpit',
    isMenu: true,
    leaf: true,
    order: 1,
    time: true,
    refresh: true,
    limitDays: 1, // 24小时
  },
];

// 告警中心 3
const alarmCenter: OptionalPropMenu[] = [
  {
    parentId: 0,
    id: 3,
    name: '告警中心',
    path: '/alarmCenter',
    icon: 'db-icon-alarm',
    isMenu: true,
    order: 3,
  },
  {
    parentId: 3,
    id: 301,
    name: '告警列表',
    path: '/alarmCenter/alarm',
    isMenu: true,
    leaf: true,
    order: 1,
    time: true,
    refresh: true,
  },
  {
    parentId: 3,
    id: 302,
    name: '告警通知',
    path: '/alarmCenter/notice',
    isMenu: true,
    leaf: true,
    order: 2,
    time: true,
    refresh: true,
  },
  {
    parentId: 3,
    id: 303,
    name: '故障列表',
    path: '/alarmCenter/rootCause',
    isMenu: true,
    leaf: true,
    order: 3,
    time: true,
    refresh: true,
  },
  {
    parentId: 3,
    id: 304,
    name: '故障分析',
    path: '/alarmCenter/problemAnalysis',
    isMenu: true,
    leaf: true,
    order: 4,
    time: true,
    refresh: true,
  },

  {
    parentId: 3,
    id: 311,
    name: '告警详情',
    path: '/alarmCenter/alarmDetail',
    menuId: 301,
    isStatic: true,
  },
  {
    parentId: 3,
    id: 313,
    name: '根因分析',
    path: '/alarmCenter/rootCauseAnalysis',
    isStatic: true,
    menuId: 303,
    time: true,
  },
  {
    parentId: 3,
    id: 314,
    name: '问题详情',
    path: '/alarmCenter/problemDetail',
    isStatic: true,
    menuId: 303,
    // time: true,
    // refresh: true,
  },
];

// 应用性能 4
const appMonitor: OptionalPropMenu[] = [
  {
    parentId: 0,
    id: 4,
    name: '应用性能',
    path: '/appMonitor',
    icon: 'db-icon-app-service',
    isMenu: true,
    order: 4,
  },
  {
    parentId: 4,
    id: 401,
    name: '全局拓扑',
    path: '/appMonitor/globalTopology',
    filePath: '/appMonitor/globalTopology',
    isMenu: true,
    leaf: true,
    order: 1,
    time: true,
    refresh: true,
  },
  {
    parentId: 4,
    id: 403,
    name: '服务',
    path: '/appMonitor/service',
    isMenu: true,
    leaf: true,
    order: 3,
    time: true,
    refresh: true,
  },
  {
    parentId: 4,
    id: 404,
    name: '数据库',
    path: '/appMonitor/database',
    isMenu: true,
    leaf: true,
    order: 4,
    time: true,
    refresh: true,
  },
  {
    parentId: 4,
    id: 40401,
    name: '数据库详情',
    path: '/appMonitor/database/detail',
    filePath: '/appMonitor/serviceDetail',
    menuId: 404,
    isStatic: true,
    time: true,
    refresh: true,
  },
  {
    parentId: 4,
    id: 405,
    name: '消息队列',
    path: '/appMonitor/msgQueue',
    isMenu: true,
    leaf: true,
    order: 5,
    time: true,
    refresh: true,
  },
  {
    parentId: 4,
    id: 40501,
    name: '消息队列详情',
    path: '/appMonitor/msgQueue/detail',
    filePath: '/appMonitor/serviceDetail',
    menuId: 405,
    isStatic: true,
    time: true,
    refresh: true,
  },
  {
    parentId: 4,
    id: 406,
    name: '缓存',
    path: '/appMonitor/cache',
    isMenu: true,
    leaf: true,
    order: 6,
    time: true,
    refresh: true,
  },
  {
    parentId: 4,
    id: 40601,
    name: '缓存详情',
    path: '/appMonitor/cache/detail',
    filePath: '/appMonitor/serviceDetail',
    menuId: 406,
    isStatic: true,
    time: true,
    refresh: true,
  },
  {
    parentId: 4,
    id: 412,
    name: '外部服务',
    path: '/appMonitor/external',
    isMenu: true,
    leaf: true,
    order: 6.5,
    time: true,
    refresh: true,
  },
  {
    parentId: 4,
    id: 41201,
    name: '外部服务详情',
    path: '/appMonitor/external/detail',
    filePath: '/appMonitor/serviceDetail',
    menuId: 412,
    isStatic: true,
    time: true,
    refresh: true,
  },
  {
    parentId: 4,
    id: 407,
    name: '接口分析',
    path: '/appMonitor/serviceAnalysis',
    isMenu: true,
    leaf: true,
    order: 7,
    time: true,
    refresh: true,
  },
  {
    parentId: 4,
    id: 408,
    name: '错误分析',
    path: '/appMonitor/errors',
    isMenu: true,
    leaf: true,
    order: 8,
    time: true,
    refresh: true,
  },
  {
    parentId: 4,
    id: 409,
    name: '链路追踪',
    path: '/appMonitor/trace',
    isMenu: true,
    leaf: true,
    order: 9,
    time: true,
    refresh: true,
  },
  {
    parentId: 4,
    id: 410,
    name: '服务流',
    path: '/appMonitor/serviceFlow',
    isMenu: true,
    leaf: true,
    order: 3.5,
    time: true,
    refresh: true,
    limitDays: 1, // 24小时
  },
  {

    parentId: 4,
    id: 422,
    name: '响应时间分布',
    path: '/appMonitor/response',
    isStatic: true,
    menuId: 403,
    time: true,
    refresh: true,
  },
  {
    parentId: 4,
    id: 423,
    name: '接口调用分析',
    path: '/appMonitor/serviceCall',
    isStatic: true,
    menuId: 403,
    time: true,
    refresh: true,
  },
  {
    parentId: 4,
    id: 424,
    name: '接口调用出入口详情',
    path: '/appMonitor/serviceCallDetail',
    isStatic: true,
    menuId: 403,
    time: true,
    refresh: true,
  },
  {
    parentId: 4,
    id: 425,
    name: '接口详情',
    path: '/appMonitor/resourceDetail',
    isStatic: true,
    menuId: 407,
    time: true,
    refresh: true,
  },
  {
    parentId: 4,
    id: 426,
    name: '调用链详情',
    path: '/appMonitor/traceDetail',
    menuId: 409,
    isStatic: true
  },
  {
    parentId: 4,
    id: 427,
    name: '服务详情',
    path: '/appMonitor/serviceDetail',
    isStatic: true,
    menuId: 403,
    time: true,
    refresh: true,
  },
  {
    parentId: 4,
    id: 428,
    name: '服务实例详情',
    path: '/appMonitor/serviceInstance',
    isStatic: true,
    menuId: 403,
    time: true,
    refresh: true,
  },
  {
    parentId: 4,
    id: 429,
    name: '错误详情',
    path: '/appMonitor/errorDetail',
    isStatic: true,
    menuId: 408,
    time: true,
    refresh: true,
  },
  {
    parentId: 4,
    id: 430,
    name: 'Profiling',
    path: '/appMonitor/hotMethods',
    isStatic: true,
    menuId: 407,
    time: true,
    refresh: true,
  },
  {
    parentId: 4,
    id: 432,
    name: '线程池监控',
    path: '/appMonitor/threadPool',
    isStatic: true,
    menuId: 403,
    time: true,
    refresh: true,
  },
  {
    parentId: 4,
    id: 433,
    name: '对象池监控',
    path: '/appMonitor/objectPool',
    isStatic: true,
    menuId: 403,
    time: true,
    refresh: true,
  },
  {
    parentId: 4,
    id: 434,
    name: 'HTTP连接池监控',
    path: '/appMonitor/httpConnPool',
    isStatic: true,
    menuId: 403,
    time: true,
    refresh: true,
  },
  {
    parentId: 4,
    id: 435,
    name: '数据库连接池监控',
    path: '/appMonitor/dbConnPool',
    isStatic: true,
    menuId: 403,
    time: true,
    refresh: true,
  },
];

// AI 可观测 18
const aiMonitor: OptionalPropMenu[] = [
  {
    parentId: 0,
    id: 18,
    name: 'Agent观测',
    path: '/aiMonitor',
    icon: 'db-icon-agent',
    isMenu: true,
    order: 4.5,
  },
  {
    parentId: 18,
    id: 1801,
    name: 'Agent列表',
    path: '/aiMonitor/applications',
    filePath: '/aiMonitor/applications',
    isMenu: true,
    leaf: true,
    order: 1,
    time: true,
    refresh: true,
  },
  {
    parentId: 18,
    id: 1802,
    name: 'Agent拓扑',
    path: '/aiMonitor/topology',
    filePath: '/aiMonitor/topology',
    isMenu: true,
    leaf: true,
    order: 2,
    time: true,
    refresh: true,
  },
  {
    parentId: 18,
    id: 1808,
    name: '技能调用',
    path: '/aiMonitor/skillCalls',
    filePath: '/aiMonitor/skillCalls',
    isMenu: true,
    leaf: true,
    order: 3,
    time: true,
    refresh: true,
  },
  {
    parentId: 18,
    id: 1805,
    name: '工具调用',
    path: '/aiMonitor/toolCalls',
    filePath: '/aiMonitor/toolCalls',
    isMenu: true,
    leaf: true,
    order: 4,
    time: true,
    refresh: true,
  },
  {
    parentId: 18,
    id: 1804,
    name: '模型调用',
    path: '/aiMonitor/modelCalls',
    filePath: '/aiMonitor/modelCalls',
    isMenu: true,
    leaf: true,
    order: 5,
    time: true,
    refresh: true,
  },
  {
    parentId: 18,
    id: 1803,
    name: '对话追踪',
    path: '/aiMonitor/sessions',
    filePath: '/aiMonitor/sessions',
    isMenu: true,
    leaf: true,
    order: 6,
    time: true,
    refresh: true,
  },
  {
    parentId: 18,
    id: 1806,
    name: 'Token分析',
    path: '/aiMonitor/tokens',
    filePath: '/aiMonitor/tokens',
    isMenu: true,
    leaf: true,
    order: 7,
    time: true,
    refresh: true,
  },
  {
    parentId: 18,
    id: 1807,
    name: '错误分析',
    path: '/aiMonitor/errors',
    filePath: '/aiMonitor/errors',
    isMenu: true,
    leaf: true,
    order: 8,
    time: true,
    refresh: true,
  },
];

// 基础设施 5
const infrastructure: OptionalPropMenu[] = [
  {
    parentId: 0,
    id: 5,
    name: '基础设施',
    path: '/infrastructure',
    icon: 'db-icon-infrastructure',
    isMenu: true,
    order: 5,
  },
  {
    parentId: 5,
    id: 501,
    name: '主机',
    path: '/infrastructure/host',
    isMenu: true,
    leaf: true,
    order: 1,
    time: true,
    refresh: true,
  },
  {
    parentId: 5,
    id: 502,
    name: 'Docker容器',
    path: '/infrastructure/docker',
    isMenu: true,
    leaf: true,
    order: 2,
    time: true,
    refresh: true,
  },
  {
    parentId: 5,
    id: 503,
    name: 'Kubernetes',
    path: '/infrastructure/cluster',
    isMenu: true,
    leaf: true,
    order: 3,
    time: true,
    refresh: true,
  },
  {
    parentId: 5,
    id: 504,
    name: '进程',
    path: '/infrastructure/process',
    isMenu: true,
    leaf: true,
    order: 4,
    time: true,
    refresh: true,
  },

  {
    parentId: 5,
    id: 511,
    name: '主机详情',
    path: '/infrastructure/hostDetail',
    isStatic: true,
    menuId: 501,
    time: true,
    refresh: true,
  },
  {
    parentId: 5,
    id: 514,
    name: 'Kubernetes详情',
    path: '/infrastructure/clusterDetail',
    isStatic: true,
    menuId: 503,
    time: true,
    refresh: true,
  },
  {
    parentId: 5,
    id: 515,
    name: 'Node分析',
    path: '/infrastructure/node',
    isStatic: true,
    menuId: 503,
    time: true,
    refresh: true,
  },
  {
    parentId: 5,
    id: 516,
    name: 'Namespace',
    path: '/infrastructure/namespace',
    isStatic: true,
    menuId: 503,
    time: true,
    refresh: true,
  },
  {
    parentId: 5,
    id: 517,
    name: 'Namespace详情',
    path: '/infrastructure/namespaceDetail',
    isStatic: true,
    menuId: 503,
    time: true,
    refresh: true,
  },
  {
    parentId: 5,
    id: 518,
    name: 'Workloads',
    path: '/infrastructure/workload',
    isStatic: true,
    menuId: 503,
    time: true,
    refresh: true,
  },
  {
    parentId: 5,
    id: 519,
    name: 'Workload详情',
    path: '/infrastructure/workloadDetail',
    isStatic: true,
    menuId: 503,
    time: true,
    refresh: true,
  },
  {
    parentId: 5,
    id: 520,
    name: 'Pods',
    path: '/infrastructure/pod',
    isStatic: true,
    menuId: 503,
    time: true,
    refresh: true,
  },
  {
    parentId: 5,
    id: 521,
    name: 'Pod详情',
    path: '/infrastructure/podDetail',
    isStatic: true,
    menuId: 503,
    time: true,
    refresh: true,
  },
  {
    parentId: 5,
    id: 522,
    name: 'Services',
    path: '/infrastructure/service',
    isStatic: true,
    menuId: 503,
    time: true,
    refresh: true,
  },
  {
    parentId: 5,
    id: 523,
    name: 'Service详情',
    path: '/infrastructure/serviceDetail',
    isStatic: true,
    menuId: 503,
    time: true,
    refresh: true,
  },
  {
    parentId: 5,
    id: 524,
    name: 'Node详情',
    path: '/infrastructure/nodeDetail',
    isStatic: true,
    menuId: 503,
    time: true,
    refresh: true,
  },
  {
    parentId: 5,
    id: 525,
    name: '进程详情',
    path: '/infrastructure/processDetail',
    isStatic: true,
    menuId: 504,
    time: true,
    refresh: true,
  },
  {
    parentId: 5,
    id: 526,
    name: '容器详情',
    path: '/infrastructure/dockerDetail',
    isStatic: true,
    menuId: 502,
    time: true,
    refresh: true,
  },
  // 技术组件（已下线）
  // 负载均衡 nginxTracing（已下线）
];

// 网络性能 7
const npm: OptionalPropMenu[] = [
  {
    parentId: 0,
    id: 7,
    name: '网络性能',
    path: '/npm',
    icon: 'db-icon-npm',
    isMenu: true,
    leaf: false,
    order: 7,
    time: true,
    refresh: true,
  },
  {
    parentId: 7,
    id: 702,
    name: '网络分析',
    path: '/npm/analysis',
    isMenu: true,
    leaf: true,
    order: 2,
    time: true,
    refresh: true,
  },
  {
    parentId: 7,
    id: 703,
    name: '网络拓扑',
    path: '/npm/topology',
    isMenu: true,
    leaf: true,
    order: 3,
    time: true,
    refresh: true,
  },
  {
    parentId: 7,
    id: 704,
    name: 'DNS分析',
    path: '/npm/dns',
    isMenu: true,
    leaf: true,
    order: 4,
    time: true,
    refresh: true,
  },
];


// 安装部署 12
const deployInstall: OptionalPropMenu[] = [
  {
    parentId: 0,
    id: 12,
    name: '安装部署',
    path: '/deploy',
    filePath: RouterViewTemp,
    icon: 'db-icon-deploy',
    isMenu: true,
    order: 9.5,
  },
  {
    parentId: 12,
    id: 1201,
    name: '数据接入',
    path: '/deploy/access',
    filePath: '/deployInstall',
    isMenu: true,
    leaf: true,
    order: 1,
  },
  {
    parentId: 12,
    id: 1202,
    name: '部署状态',
    path: '/deploy/status',
    filePath: '/deployInstall/status',
    isMenu: true,
    leaf: true,
    order: 2,
  },
];

// 配置管理 10
const config: OptionalPropMenu[] = [
  {
    parentId: 0,
    id: 10,
    name: '配置管理',
    path: '/config',
    filePath: RouterViewTemp,
    icon: 'db-icon-deploy',
    isMenu: true,
    order: 10,
  },
  {
    parentId: 10,
    id: 1002,
    name: '部署状态',
    path: '/config/status',
    filePath: '/configStatus',
    isMenu: true,
    leaf: true,
    order: 2,
  },
  {
    parentId: 10,
    id: 1003,
    name: '配置管理',
    path: '/config/manage',
    filePath: '/configManage',
    icon: 'db-icon-deploy',
    isMenu: true,
    order: 3,
  },

  /* 配置管理的三级、四级菜单 */
  // 实体监控
  {
    parentId: 1003,
    id: 1010,
    name: '实体监控',
    path: '/config/entity',
    filePath: RouterViewTemp,
    isMenu: true,
    order: 1,
  },
  {
    parentId: 1010,
    id: 1011,
    name: '服务监控',
    path: '/config/service',
    filePath: '/configManage/entity/service',
    isMenu: true,
    leaf: true,
    order: 1,
  },
  {
    parentId: 1010,
    id: 1013,
    name: '进程监控',
    path: '/config/process',
    filePath: '/configManage/entity/process',
    isMenu: true,
    leaf: true,
    order: 3,
  },
  // 拓扑配置
  {
    parentId: 1003,
    id: 1050,
    name: '拓扑配置',
    path: '/config/relationest',
    filePath: '/configManage/entity/relation',
    isMenu: true,
    order: 1.5,
  },
  // 告警配置
  {
    parentId: 1003,
    id: 1020,
    name: '告警配置',
    path: '/config/alarm',
    filePath: '/configManage/alarm',
    isMenu: true,
    leaf: true,
    order: 2,
  },
  {
    parentId: 1020,
    id: 1021,
    name: '检测规则',
    path: '/config/rule',
    filePath: '/configManage/alarm',
    isMenu: false,
    isStatic: true,
    menuId: 1020,
    leaf: true,
    order: 1,
  },
  {
    parentId: 1020,
    id: 1035,
    name: '模型配置',
    path: '/config/llm',
    filePath: '/configManage/llm',
    isMenu: true,
    leaf: true,
    order: 2.5,
  },
  {
    parentId: 1003,
    id: 1036,
    name: '登录设置',
    path: '/config/login',
    filePath: '/configManage/login',
    isMenu: true,
    leaf: true,
    order: 2.6,
  },
  {
    parentId: 1003,
    id: 1030,
    name: 'Databuff AI配置',
    path: '/config/ai',
    filePath: '/configManage/ai',
    isMenu: true,
    order: 2.1,
  },

  // 非菜单
  {
    parentId: 1003,
    id: 1061,
    name: '推荐规则',
    path: '/configManage/alarm/rulePreset',
    filePath: '/configManage/alarm/rulePreset',
    isStatic: true,
    menuId: 1020,
  },
  {
    parentId: 1003,
    id: 1062,
    name: '新建规则',
    path: '/configManage/alarm/ruleSetting',
    filePath: '/configManage/alarm/ruleSetting',
    isStatic: true,
    menuId: 1020,
  },
  {
    parentId: 1003,
    id: 1064,
    name: '新建响应策略',
    path: '/configManage/alarm/responseSetting',
    filePath: '/configManage/alarm/responseSetting',
    isStatic: true,
    menuId: 1020,
  },
  {
    parentId: 10,
    id: 1067,
    name: '更新包管理',
    path: '/config/agentPackages',
    filePath: '/configStatus/agentPackages',
    isStatic: true,
    menuId: 1002,
  },
  {
    parentId: 10,
    id: 1070,
    name: '运行日志',
    path: '/config/runLog',
    filePath: '/configStatus/runLog',
    isStatic: true,
    menuId: 1002,
  },
  // 原系统管理
  {
    parentId: 1003,
    id: 1082,
    name: '角色管理',
    path: '/sysManage/role',
    isMenu: true,
    leaf: true,
    order: 4,
  },
  {
    parentId: 1003,
    id: 1093,
    name: '组织管理',
    path: '/sysManage/org',
    isMenu: true,
    leaf: true,
    order: 4,
  },
  {
    parentId: 1003,
    id: 1083,
    name: 'License管理',
    path: '/sysManage/license',
    isMenu: true,
    leaf: true,
    order: 5,
  },
  {
    parentId: 1003,
    id: 1084,
    name: '通知管理',
    path: '/sysManage/notice',
    isMenu: true,
    leaf: true,
    order: 6,
  },
  {
    parentId: 1003,
    id: 1085,
    name: '系统设置',
    path: '/sysManage/setting',
    filePath: RouterViewTemp,
    isMenu: true,
    order: 7,
  },
  {
    parentId: 1085,
    id: 1086,
    name: '基础设置',
    path: '/sysManage/basic',
    isMenu: true,
    leaf: true,
    order: 1,
  },
  {
    parentId: 1085,
    id: 1087,
    name: '系统事件',
    path: '/sysManage/systemEvent',
    isMenu: true,
    leaf: true,
    order: 2,
    time: true,
    refresh: true,
  },
  {
    parentId: 1003,
    id: 1088,
    name: '操作审计',
    path: '/sysManage/operationAudit',
    isMenu: true,
    leaf: true,
    order: 8,
  },

  {
    parentId: 10,
    id: 1089,
    name: '系统事件详情',
    path: '/sysManage/eventDetail',
    filePath: '/alarmCenter/eventDetail',
    menuId: 1003,
    isStatic: true,
  },
  {
    parentId: 10,
    id: 1090,
    name: '系统检测规则',
    path: '/sysManage/systemRule',
    filePath: '/sysManage/systemRule',
    menuId: 1003,
    isStatic: true,
  },
  {
    parentId: 10,
    id: 1091,
    name: '新建系统规则',
    path: '/sysManage/ruleSetting',
    filePath: '/configManage/alarm/ruleSetting',
    isStatic: true,
    menuId: 1003,
  },
];

// 个人中心 88
const personal: OptionalPropMenu[] = [
  {
    parentId: 0,
    id: 88,
    name: '个人中心',
    path: '/personal',
    isMenu: false,
    isStatic: true,
  },
];

const routeData: FullPropMenu[] = [
  ...aiPlatform.map(t => ({ ...t, module: t.module || 'aiPlatform' })),
  ...cockpit.map(t => ({ ...t, module: t.module || 'cockpit' })),
  ...alarmCenter.map(t => ({ ...t, module: t.module || 'alarmCenter' })),
  ...appMonitor.map(t => ({ ...t, module: t.module || 'appMonitor' })),
  ...aiMonitor.map(t => ({ ...t, module: t.module || 'aiMonitor' })),
  ...infrastructure.map(t => ({ ...t, module: t.module || 'infrastructure' })),
  ...npm.map(t => ({ ...t, module: t.module || 'npm' })),
  ...deployInstall.map(t => ({ ...t, module: t.module || 'deployInstall' })),
  ...config.map(t => ({ ...t, module: t.module || 'config' })),
  ...personal.map(t => ({ ...t, module: t.module || 'personal' })),
].map(t => ({
  ...t,
  hidden: !!t.hidden,
  filePath: t.filePath || t.path,
  icon: t.icon || '',
  isMenu: !!t.isMenu,
  leaf: !!t.leaf,
  order: t.order || 99,
  isStatic: !!t.isStatic,
  menuId: t.menuId || t.id,
  time: t.time || false,
}));

// ID 不能重复
const routeIds = routeData.map(t => t.id);
const duplicateIds = routeIds.filter((id, index) => routeIds.indexOf(id) !== index);
if (duplicateIds.length) {
  console.log(`%c❗❗❗route id 重复：${duplicateIds.join(', ')}❗❗❗`, 'color: red');
}

// 存在静态菜单
const staticMenu = routeData.filter(t => t.isMenu && t.isStatic).map(t => t.path);
if (staticMenu.length) {
  console.log(`%c❗❗❗route menu 存在静态菜单：${staticMenu.join(', ')}❗❗❗`, 'color: red');
}

export default routeData;
